// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog: dynamic(() => import("./Blog")),
  call_to_action: dynamic(() => import("./CallToAction")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  t_estimonials: dynamic(() => import("./TEstimonials")),
  text_with_image: dynamic(() => import("./TextWithImage")),
};
